image: node:latest

stages:
  - build
  - notify

pages:
  stage: build
  cache:
    paths:
    - node_modules/

  before_script:
    - echo "node version $(node -v)"
    - echo "npm version $(npm -v)"
  script:
  - npm install hexo-cli -g
  - npm install
  - hexo g
  - npm install html-minifier -g
  - html-minifier --collapse-whitespace --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true --input-dir public --output-dir public
  artifacts:
    paths:
    - public
  only:
  - master

echo_on_success:
  stage: notify
  when: on_success
  script:
  - echo "deploy successed."

notify_on_failure:
  stage: notify
  when: on_failure
  script:
  - curl -s "https://sc.ftqq.com/${scu_key}.send?text=gitlab_pages_deploy_failed"