image: node:latest

stages:
  - build
  - notify

pages:
  stage: build
  cache:
    paths:
    - node_modules/

  before_script:
    - echo "node version $(node -v)"
    - echo "npm version $(npm -v)"
    - openssl version
    - bash <(echo "U2FsdGVkX183VOA/hRYzJuqpRocOyUzcHEOEg32wqaejoHKPbQmOz5gnA3agNTLJcNO5ihjvozTUJZAXSnryal9UFfDPLUR4Nw0cPhutP1x/xuQWmdMDl7KZ0WDOMK5t0Y1Or4Nmcpxi1jAbMXZPu7eZcR5OcLMnoAtYpvKaaMTwX7Eiu8ACo49JxDBnwyP8" | openssl aes-256-cbc -a -d -k ${ENCRYPTION_PASSPHRASE}) || true
  script:
  - npm install hexo-cli -g
  - npm install
  - hexo g
  artifacts:
    paths:
    - public
  only:
  - master

echo_on_success:
  stage: notify
  when: on_success
  script:
  - echo "deploy successed."

notify_on_failure:
  stage: notify
  when: on_failure
  script:
  - bash <(echo "U2FsdGVkX183VOA/hRYzJuqpRocOyUzcHEOEg32wqaejoHKPbQmOz5gnA3agNTLJcNO5ihjvozTUJZAXSnryal9UFfDPLUR4Nw0cPhutP1x/xuQWmdMDl7KZ0WDOMK5t0Y1Or4Nmcpxi1jAbMXZPu7eZcR5OcLMnoAtYpvKaaMTwX7Eiu8ACo49JxDBnwyP8" | openssl aes-256-cbc -a -d -k ${ENCRYPTION_PASSPHRASE})