image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  before_script:
    - git config --global user.name "Akame-moe"
    - git config --global user.email "me@gentlehu.com"
  script:
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master

