language: node_js
node_js: stable

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "Alisa_Destiny"
  - git config --global user.email "me@gentlehu.com"

install:
  - npm install hexo -g
  
script:
  - hexo clean
  - hexo g
  - cd ./public
  - git init
  - git add .
  - git commit "auto deploy by travis-ci"
  - git push "https://Alisa_Destiny:${CODING_TOKEN}@${CODING_REF}" master:master
  
after_success:
  - echo "deploy successfully"
